/*
-- Query: SELECT * FROM miniworddb.word
LIMIT 0, 1000

-- Date: 2023-01-18 18:16
*/
INSERT INTO `` (`ENG`,`KOR`) VALUES ('a','하나의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('abandon','버리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('able','할 수 있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aboard','배로');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('abort','유산하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('about','-에 대하여');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('above','-보다 위에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('abroad','외국으로');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('absent','부재의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('absolute','절대의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('absorb','흡수하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('abstract','추상적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('absurd','불합리한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('abundant','풍부한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('abuse','남용');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('academy','학술원');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accelerate','가속하다 속도가 가해지다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accent','액센트');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accept','받아들이다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('access','접근');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accident','뜻밖의 사건');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accommodate','수용하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accompany','동반하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accomplish','이루다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accord','일치하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('account','설명하다 계산');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accumulate','축적하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accurate','정확한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('accuse','고발하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('achieve','성취하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('acid','산 신');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('acknowledge','인정하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('acquaint','알리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('acquire','얻다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('acquisition','획득');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('across','가로질러');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('act','vi행동하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('activate','활동적으로 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('actual','현실의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('acute','날카로운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('adapt','적용시키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('add','추가하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('addict','열중하게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('address','말을 걸다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('adequate','충분한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('adjust','맞추다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('administer','관리하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('admire','감복하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('admission','입장');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('admit','받아들이다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('adolescent','청년기의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('adopt','채용하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('adult','성인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('advance','나아가다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('advantage','유리한 입장');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('adventure','모험 모험하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('adverse','거꾸로의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('advertize','광고하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('advise','충고하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('advocate','변호사');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aesthetic','미적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('affair','일');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('affect','영향을 주다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('affection','애정');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('affiliate','회원으로 가입시키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('afford','여유가 있다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('afraid','두려워하여');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('after','후에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('afternoon','오후');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('again','다시');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('against','…에 반대하여');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('age','연령');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('agency','기능');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('agenda','안건');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('agent','대리인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aggressive','침략적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ago','이전에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('agree','동의하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('agriculture','농업');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ahead','전방에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aid','도와 주다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aim','겨누다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('air','공기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('airplane','비행기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aircraft','항공기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('airline','정기항공');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('airport','공항');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aisle','측면복도');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('alert','빈틈없는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('alien','외국의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('alike','비슷한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('alive','살아있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('all','모든');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('allocate','할당하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('allow','허락하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ally','동맹하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('almost','거의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('alone','다만 홀로(혼자서)');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('along','-을 따라');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('alongside','-의 곁에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aloud','큰 소리로');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('already','이미');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('alright','더할나위없이');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('also','-도 또한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('alter','바꾸다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('alternative','어느 한쪽의 양자택일');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('although','비록 -일지라도');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('altogether','전혀');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('always','늘');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('A.M.','오전');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('amaze','깜짝 놀라게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ambassador','대사');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ambition','야심');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('among','-중에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('amount','(금액이)-이 되다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('amplify','확대하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('amuse','재미나게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('analyze','분해하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('anchor','닻');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ancient','옛날의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('and','및');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('angel','천사');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('anger','성');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('angle','각');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('animal','동물');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('anniversary','기념일 예년의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('announce','알리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('annoy','귀찮게하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('annual','일년의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('another','또 하나');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('answer','대답');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ant','개미');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('anticipate','예기하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('anxiety','근심');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('anxious','걱정되는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('any','어떤');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('apart','떨어져서');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('apology','사과');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('apparent','명백한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('appeal','간청하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('appear','나타나다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('apple','사과');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('applicant','지원자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('apply','(물건을)대다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('appoint','지정하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('appreciate','감상하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('approach','다가가다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('appropriate','적당한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('approve','시인하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('approximate','어림셈의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('architect','건축가');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('architecture','건축');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('archive','기록보관소');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('area','면적');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('argue','논하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('arise','생기다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('arm','팔');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('army','육군');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('around','사방에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('arrange','가지런히 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('arrest','체포하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('arrive','도착하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('arrow','화살');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('art','예술');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('article','물품');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('artificial','인공의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('as','-와 같은 정도로');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ash','회');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aside','곁에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ask','묻다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('asleep','잠들은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aspect','관점');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aspire','열망하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('assault','습격');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('assemble','모으다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('assert','단언하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('assess','(세금 등을)사정하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('asset','자산');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('assign','할당하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('assist','돕다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('associate','연상하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('assume','취하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('assure','보증하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('astonish','놀라게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('at','-에서');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('athlete','운동가');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('atmosphere','대기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('atom','원자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attach','붙이다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attack','공격하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attain','이르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attempt','시도하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attend','출석하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attention','주의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attitude','태도');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attorney','변호사');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attract','끌어 당기다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('attribute','속성');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('auction','경매');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('audience','청중');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aunt','아주머니');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('authentic','진짜의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('author','저자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('autobiography','자서전');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('automatic','자동의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('automobile','자동차 자동차의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('available','쓸모있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('avenue','가로수길');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('average','평균');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('avoid','피하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('await','기다리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('awake','깨우다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('award','상');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('aware','알고 있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('away','떨어져서');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('awesome','무서운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('awful','두려운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('awkward','어색한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('baby','갓난아이, 막내   관심사, 골치아픈 일,');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('back','등');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('background','배경');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bad','나쁜');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bake','굽다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('balance','균형');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ball','공');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('balloon','기구');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ban','금지');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('band','그룹');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bang','강타');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bank','둑');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bankrupt','파산자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bar','막대기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bare','벌거벗은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bargain','매매');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bark','짖다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('barn','헛간');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('barrier','장벽');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('base','기초');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('baseball','야구');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('basic','기본의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('basis','기초');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('basket','바구니');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('basketball','농구');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bat','배트');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bath','목욕');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bathroom','욕실');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('battery','전지');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('battle','전투');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bay','만');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('be','-이다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beach','해안');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beam','광선');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bean','콩');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bear','나르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beard','턱수염');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beast','짐승');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beat','치다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beauty','아름다움');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('because','왜냐하면');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('become','-이 되다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bed','침대');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bedroom','침실 성적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bee','꿀벌');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beef','쇠고기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beer','맥주');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('before','앞에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beg','청하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('begin','시작하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('behalf','위함');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('behave','행동하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('behavior','행동');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('behind','뒤에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('believe','믿다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bell','종');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('belong','속하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('below','아래에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bend','구부리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beneath','-의 바로 아래에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('benefit','이익');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('berry','액과');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beside','-의 곁에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bet','걸다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('betray','배반하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('between','-의 사이에 사이에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('beyond','저편에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bias','치우침');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bible','성서, 성경');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bicycle','자전거 자전거를 타다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('big','큰');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bill','계산서');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('billion','10억');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bin','궤');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bind','매다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('biography','전기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('biology','생물학');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bird','새');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('birth','출생');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('birthday','생일');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bishop','주교');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bit','bite의 과거(분사) 작은 조각');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bite','물다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bitter','쓴');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('black','검은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blame','책망하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blank','공백');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blanket','담요');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blast','돌풍');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blend','혼합하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bless','축복하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blind','눈먼');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blink','(눈을)깜빡거리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('block','덩어리');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blonde','(살결이 흰)금발의 여성');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blood','피');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bloom','쇳덩이');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blossom','(과수의)꽃');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blow','강타');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('blue','푸른');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('board','널빤지');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('boat','배');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('body','신체');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('boil','끓다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bold','대담한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bomb','폭탄 폭격하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bond','결속');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bone','뼈');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('book','책');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('boom','굉음');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('boost','뒤를 밀기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('boot','목이 긴 구두');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('border','가장자리');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bore','고조');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('borrow','빌다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('boss','두목');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('both','쌍방의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bother','괴롭히다 근심하다 귀찮음');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bottle','병');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bottom','밑바닥');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bounce','뛰어오르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('boundary','경계');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bow','절');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bowl','사발');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('boy','소년');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brain','뇌');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brake','브레이크');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('branch','가지');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brand','상표');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brave','용감한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bread','빵');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('break','부수다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('breakfast','아침밥');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('breast','가슴');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('breathe','숨쉬다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('breed','기르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('breeze','미풍');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brew','양조하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brick','벽돌');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bride','신부');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bridge','다리');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brief','단시간의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bright','밝은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brilliant','빛나는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bring','가져오다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('broad','(폭이)넓은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('broadcast','방송하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brother','형제');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brown','갈색의 갈색');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brush','솔');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('brute','야수 짐승같은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bubble','거품 거품이 일다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('budget','예산');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bug','벌레');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('build','짓다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bulk','부피');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bull','황소');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bullet','탄환');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bully','약한 자를 못살게 구는 자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bump','충돌 부딪치다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bunch','송이');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bundle','다발');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('burden','후렴');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('burn','시내');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('burst','파열하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bury','묻다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('bush','덤불');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('business','직업');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('busy','바쁜');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('but','그러나 다만 (-을)제외하고');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('butcher','정육점주인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('button','단추 단추를 채우다 단추로 채워지다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('buy','사다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('buzz','윙윙거리는 소리');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('by','곁에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cab','택시');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cabin','선실');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cable','해저전신');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cage','새장');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('calculate','계산하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('calendar','달력');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('call','부르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('calm','평온한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('can','au-할 수 있다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cancel','취소하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cancer','암');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('candidate','지원자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('candy','사탕과자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('canvas','돛베');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cap','모자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('capable','할 수 있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cape','곶');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('capital','수위의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('captain','우두머리(chief)');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('caption','표제');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('capture','붙잡다(=catch)');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('car','자동차');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('care','걱정');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('career','경력');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('carrot','당근');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('carry','나르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cart','(2륜)짐마차');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('carve','조각하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('case','경우');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cash','현금 현금으로 바꾸다 현금의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cast','던지다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('castle','성');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('casual','우연한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cat','고양이');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('catch','붙잡다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('category','범주');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cater','음식물을 마련하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cathedral','대성당');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cattle','소');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('causal','원인의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cause','원인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('caution','조심');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cave','동굴 굴을 파다 꺼지다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cease','그만두다 그치다 중지');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ceiling','천장');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('celebrate','경축하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('celebrity','명성');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cell','작은 방');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('censor','검열관');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('century','1세기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('certain','확신하는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('certificate','증명서');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chain','사슬');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chair','의장');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chairman','의장');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('challenge','도전');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chamber','방');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chance','우연');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('change','변화');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chaos','혼돈');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('character','인격');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('characteristic','특유한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('charge','요금');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('charity','자비');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('charm','매력');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chase','쫓다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chat','잡담');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cheap','값싼');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('check','방해');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cheek','볼');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cheer','갈채');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chef','쿡');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chemical','화학의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chemistry','화학');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chest','가슴팍');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chew','씹다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chief','우두머리');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('child','아이');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chill','차가움');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chin','턱(끝) 턱에 대다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chip','(나무)토막');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('choir','(교회의)성가대');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('choose','고르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chop','(도끼 등으로)자르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chorus','합창');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('chronic','만성의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('church','교회');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cigarette','궐련');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cinema','영화관');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('circle','원');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('circulate','순환하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('circumstance','환경');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cite','인용하다(quote)');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('citizen','시민');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('city','도시');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('civil','시민의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('claim','요구하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clap','짝짝');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clarify','맑게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clash','충돌하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('class','계급');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('classic','고전의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('classify','분류하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('classroom','교실');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clause','조항');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clay','찰흙');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clean','청결한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clear','맑은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clerk','서기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clever','영리한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('client','소송의뢰인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cliff','절벽');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('climate','기후');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('climb','기어 오르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cling','밀착하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clinic','병원');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clip','가위로 자르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clock','시계');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('close','닫다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cloth','천');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cloud','구름');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('club','클럽');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('clue','단서');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cluster','떼');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('coach','역마차');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('coal','석탄');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('coast','연안');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('code','법전');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('coin','화폐');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('coincide','일치하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cold','추운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('collaborate','공동으로 일하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('collapse','붕괴');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('collar','칼라');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('colleague','동료');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('collect','모으다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('college','단과대학');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('colony','식민지');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('color','착색하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('column','(신문 등의)난');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('combat','격투하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('combine','결합하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('come','오다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('comedy','희극');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('comfort','위안');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('command','명령하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('commence','시작하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('comment','논평');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('commerce','상업');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('commission','위임');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('commit','위탁하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('committee','위원회');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('commodity','상품');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('communicate','알리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('communist','공산주의자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('community','공동생활체');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('companion','동료');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('company','교제');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compare','비교하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compatible','양립할 수 있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compel','억지로 -시키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compensate','배상하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compete','경쟁하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('competent','능력있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compile','편찬하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('complain','불평하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('complement','보완하는 것');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('complete','완성하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('complex','합성물');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('complicate','복잡하게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('component','구성하는 성분');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compose','구성하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compound','성분 등을 혼합하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('comprehensive','이해력있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('comprise','포함하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compromise','타협 타협하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('compulsory','의무적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conceal','숨기다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conceive','상상하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('concentrate','집중하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('concept','개념');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('concern','관계하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('concert','연주회');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conclude','결정하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('concrete','구체적인 응고물');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('condemn','나무라다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('condition','조건');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conduct','행위 이끌다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('confer','주다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('confess','실토하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('confident','확신하는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('confine','국경');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('confirm','확인하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conflict','투쟁');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conform','일치시키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('confront','직면하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('confuse','혼란시키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('congratulate','축하하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('congress','회의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('connect','잇다 이어지다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conscience','양심');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conscious','의식적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('consensus','(의견 등의)일치');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('consent','승낙하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conserve','보존하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('consider','숙고하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('consist','-으로 이루어지다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('consistent','시종일관한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('constant','불변의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('constitute','구성하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('constrain','강제하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('construct','건조하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('consult','상의하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('consume','소비하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contact','접촉');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contain','내포하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contemporary','현대의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contend','싸우다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('content','만족하여');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contest','겨루다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('context','문맥');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('continent','자제심이 있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('continue','계속하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contract','계약');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contradict','반박하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contrary','반대의 반대 거꾸로');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contrast','대조');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('contribute','기부하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('control','억제하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('controversy','논쟁');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('convenient','편리한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('convention','관례');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('conversation','회화');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('convert','바꾸다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('convey','나르다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('convict','유죄로 판결하다 죄수');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('convince','확신시키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cook','요리하다 요리사');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cookie','쿠키');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cool','서늘한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cooperate','협동하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('coordinate','동격의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cop','순경');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cope','코우프(성직자의 긴 겉옷)');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('copy','사본');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('copyright','판권');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cord','밧줄');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('core','핵심');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('corn','티눈');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('corner','모퉁이');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('corporate','법인조직의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('correct','옳은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('correspond','일치하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('corridor','복도');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('corrupt','타락한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cost','가격');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('costume','복장');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cottage','시골집');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cotton','목화');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('couch','침대');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cough','기침 기침을 하다 기침을 하여 -을 뱉어내다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('could','aucan의 과거');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('council','회의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('counsel','의논');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('count','계산');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('counter','계산하는 사람');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('counterpart','부본');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('country','나라');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('countryside','시골');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('county','주');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('couple','한 쌍');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('courage','용기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cousin','사촌');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cover','덮다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cow','위협하다 암소');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cowboy','목동');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crack','찰싹 소리내다 금가다 날카로운소리');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('craft','솜씨');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crash','도산');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crawl','네발로 기다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crazy','미친');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('create','창조하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('creature','창조물');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('credible','믿을 수 있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('credit','신용');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('creek','시내');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('creep','기다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crew','승무원');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cricket','크리켓');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crime','범죄');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('criminal','죄의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crisis','위기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crisp','파삭파삭한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('criteria','criterion의 복수형');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('critic','비평가');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('criticize','비평하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('criticism','비평');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crop','수확');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cross','십자형');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crowd','군중');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crown','왕관');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crucial','결정적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cruel','잔인한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cruise','순항하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crush','눌러 부수다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cry','소리치다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('crystal','수정');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cultivate','경작하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('culture','문화');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cupboard','찬장');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cure','치료');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('curious','이상스러운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('curl','곱슬머리 머리털을 지지다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('currency','통용');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('current','유행의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('curriculum','과목');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('curry','카레요리 카레로 맛을 내다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('curse','저주');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('curtain','커어튼');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('curve','곡선');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('custody','보호');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('custom','습관');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('customer','고객');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cut','베다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cute','귀여운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cycle','순환');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('cynical','냉소적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dad','아빠');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dairy','낙농장');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dam','댐');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('damage','손해');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('damp','축축한 습기 적시다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dance','댄스');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('danger','위험');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dare','au감히 -하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dark','어두운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('darling','귀여운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dash','돌진');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('database','데이터베이스');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('date','날짜');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('daughter','딸');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dawn','새벽 날이 새다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('day','낮');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dead','죽은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deal','양');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('death','죽음');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('debate','토론 토론하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('debt','빚');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('decade','10년간');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('decay','쇠퇴하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('decent','점잖은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('decide','결정하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('decision','결정');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deck','갑판');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('declare','선언하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('decline','기울다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('decorate','장식하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('decrease','감소하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dedicate','봉납하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deep','깊은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('defeat','패배');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('defense','방어');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('defend','방어하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('defendant','피고 피고의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deficiency','결핍');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deficit','결손');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('define','정의하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('definite','일정한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('degrade','지위를 낮추다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('degree','도');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('delay','늦추다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('delegate','파견하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('delete','삭제하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deliberate','숙고하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('delicate','미묘한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('delicious','맛있는');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('delight','즐겁게하다 즐거워하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deliver','인도하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('demand','요구하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('democracy','민주주의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('democrat','민주주의자');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('demon','악마');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('demonstrate','증명하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dense','짙은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dentist','치과의사');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deny','부정하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('department','부');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('departure','출발');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('depend','좌우되다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dependence','종속');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('depict','묘사하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deposit','예금');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('depress','억압하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deprive','빼앗다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('derive','이끌어 내다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('descend','내려오다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('describe','기술하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('description','서술');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('desert','버리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('deserve',' -할 만하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('design','디자인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('designate','가리키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('desire','바라다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('desk','책상');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('despair','절망하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('desperate','절망적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('despite','-에도 불구하고 모욕');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('destination','목적지');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('destiny','운명');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('destroy','파괴하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('destruction','파괴');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('detach','분리하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('detail','상설');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('detect','간파하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('determine','결정하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('develop','발달하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('device','고안');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('devil','악마');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('devise','고안하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('devote','바치다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('diabetes','당뇨병');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dialogue','대화');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('diary','일기');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dictate','받아쓰게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dictionary','사전');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('die','죽다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('different','다른');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('difficult','곤란한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dig','파다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dignity','위엄');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dimension','치수');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('diminish','감소하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dine','저녁식사를 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dinner','정찬');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dip','담그다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('diplomat','외교관');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('direct','지도하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dirty','더러운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disabled','불구가 된');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disadvantage','불리');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disagree','일치하지 않다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disappear','안보이게 되다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disappoint','실망시키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disaster','천재');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('discharge','짐을부리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('discipline','훈련');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disclose','나타내다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('discount','할인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('discourse','강연');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('discover','발견하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('discriminate','분별하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('discuss','토론하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disease','병');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disgust','불쾌하게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dish','접시');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dismiss','떠나게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disorder','난잡');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('displace','바꾸어놓다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('display','보이다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dispose','배열하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dispute','논쟁하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disrupt','분열시키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('distant','떨어진');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('distort','찌그러뜨리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('distract','전환시키다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('distribute','분배하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('district','지구');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('disturb','교란하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dive','뛰어들다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('diverse','다양한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('divide','나누다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('divine','신의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('divorce','이혼');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('do','하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('doctor','박사');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('document','서류');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dog','개');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('doll','인형');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dolphin','돌고래');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('domain','영토');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('domestic','가정의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dominant','우세한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('donate','증여하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('door','문');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dose','1회복용량 투약하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dot','점');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('double','2배의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('doubt','의심');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('down','아래로');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dozen','1다스');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('draft','초고');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('drag','끌다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('drain','배수하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('draw','당기다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('drawer','제도사');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dread','두려워하다 두려움');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dream','꿈');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('drink','마시다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('drive','운전하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('drop','방울');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('drown','물에빠뜨리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('drug','약제');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dry','마른');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dual','둘의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('duck','머리를 물 속에 쑥 쳐박다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('due','지급기일이 된');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dull','둔한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dump','내버리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('during','-동안에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dust','먼지');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('duty','의무');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dwell','거주하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('dynamic','동적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('each','각각의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('eager','열심인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ear','귀');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('early','이른');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('earn','일하여 벌다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('earth','지구');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ease','안락');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('east','동쪽 동쪽의 동쪽으로');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('easy','쉬운');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('eat','먹다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('economy','절약');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('edge','끝머리');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('edit','편집하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('educate','교육하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('effect','결과');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('effective','효과적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('efficient','능률적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('effort','노력');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('egg','알');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('either','어느 하나의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('elaborate','공들인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('elect','선거하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('electric','전기의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('electronic','전자(학)의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('elegant','우아한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('element','요소');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('elementary','기본의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('elephant','코끼리');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('eliminate','제거하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('else','그 밖에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('embarrass','난처하게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('embassy','대사관');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('embrace','포옹하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('emerge','나오다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('emergency','비상사태');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('emit','방사하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('emotion','감정');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('emphasis','강조');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('empire','제국');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('employ','고용하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('empty','빈');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enclose','에워싸다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('encounter','조우');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('encourage','용기를 돋우다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('end','끝');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('endure','견디다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enemy','적');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enforce','실시하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('engage','약속하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('engine','엔진');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('engineer','기사');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enhance','향상하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enjoy','즐기다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enormous','거대한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enough','충분한');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enroll','명부에 올리다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ensure','-을 책임지다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enter','들어가다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enterprise','기획');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('entertain','즐겁게 하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('enthusiastic','열심인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('entire','전체의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('entitle','자격을 주다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('entry','들어감');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('envelope','봉투');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('environment','환경');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('envy','질투');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('episode','삽화');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('equal','같은');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('equate','같게하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('equipment','장비');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('era','시대');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('eraser','지우는 사람');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('erect','똑바로 선');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('error','잘못');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('escape','도망하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('escort','호위하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('especially','특히');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('essential','본질적인');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('establish','확립하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('estate','토지');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('estimate','어림잡다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('etc','등등');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ethical','도덕상의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ethnic','인종의');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('evacuate','비우다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('evaluate','평가하다');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('eve','저녁, 밤');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('even','-조차');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('evening','저녁');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('eventually','결국');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('ever','이전에');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('every','모든');
INSERT INTO `` (`ENG`,`KOR`) VALUES ('evident','명백한');
